### ISSUE TITLE
feat: add support for secure-port (tls) in addition to http

### ISSUE THREAD

**Issue by dmccaffery** [stefanprodan/podinfo#105]
AWS recently released a new load balancer controller with nlb-ip load balancing support in EKS, which is useful for E2E TLS termination scenarios, especially in fargate.

Adding support for secure-port to this container is useful for test / demo scenarios using nlb-ip load balancing.

Thinking of the following design:

* [x] add secure-port argument - 0 as a default value (secure port disabled)
* [x] add cert-path argument (for loading tls certificate key pair as expected from a volume mount for a tls secret) - /data/cert as a default value
* [x] add function to start a tls listener using the same handler mux

I'm happy to implement this if the community is in agreement.

**Comment by stefanprodan** [comment]
This looks like a great addition to podinfo, I imagine it can be used outside EKS with cert-manager self-signed certs.

**Comment by dmccaffery** [comment]
can you assign this to me? I'll open a PR shortly :)
