### ISSUE TITLE
Add service.annotations to the chart

### ISSUE THREAD

**Issue by pcostesi** [stefanprodan/podinfo#114]
Would it be possible to add `service.annotations` to the chart? That would enable things like [setting up CloudCDN in GKE](https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-features#associating_backendconfig_with_your_ingress) and test it with Podman before going to production.

**Comment by dmccaffery** [comment]
@stefanprodan : I will do this work over the weekend if its still here by then -- feel free to assign to me.

**Comment by stefanprodan** [comment]
Thanks @dmccaffery

**Comment by dmccaffery** [comment]
sry about that; I got extremely busy over the past month or so.
