### ISSUE TITLE
helm repo not up to date?

### ISSUE THREAD

**Issue by monotek** [stefanprodan/podinfo#115]
is there a reason the podinfo chart is not available in the latest version 5.1.2 from the flagger helm repo?
https://flagger.app/index.yaml has 5.0.0 as latest version.

I found a more recent index.yaml in the gh-pages branch: https://github.com/stefanprodan/podinfo/blob/gh-pages/index.yaml 
but whats the repo url of it?
i only can find the flagger repo in artifacthub, searching for podinfo: https://artifacthub.io/packages/helm/flagger/podinfo

**Comment by stefanprodan** [comment]
I'll delete the podinfo chart from Flagger, the podinfo repo is documented here https://github.com/stefanprodan/podinfo#install
