### ISSUE TITLE
Add imagePullSecrets to service account

### ISSUE THREAD

**Issue by Boojapho** [stefanprodan/podinfo#149]
To demonstrate using a service account for holding image pull secrets on a private repo, add `serviceAccount.imagePullSecrets: []` to the values and 

```yaml
{{- with .Values.serviceAccount.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
```

to serviceAccount.yaml

**Comment by stefanprodan** [comment]
Hi @Boojapho this change is fine with me, can you please open a PR for this? Thanks!
