### ISSUE TITLE
More labels for http_requests_total

### ISSUE THREAD

**Issue by jkremser** [stefanprodan/podinfo#153]
Currently the metric called `http_requests_total` has only one label called `status`.
Adding the same labels as defined for the histogram metric called `http_request_duration_seconds_bucket` would be nice.
Namely:
- method
- path

I think it can be obtained from the `http_request_duration_seconds_count` but it's not straightforward.

**Comment by pableeee** [comment]
I've created simple PR #186, that addresses these missing tags.

**Comment by stefanprodan** [comment]
Here is how you can use `http_request_duration_seconds_count` to measure the error rate: https://github.com/fluxcd/flagger/blob/main/pkg/metrics/observers/http.go

**Comment by stefanprodan** [comment]
Going to close this since `http_request_duration_seconds_count` is a counter just like `http_requests_total`.
