### ISSUE TITLE
Anti-pattern: HTTP Without TLS

### ISSUE THREAD

**Issue by akondasif** [stefanprodan/podinfo#162]
Dear Colleague,

We are looking to find ways to help developers find security anti-patterns, i.e., violation of security best practices in Kubernetes manifests. 

We have noticed an instance of HTTP without TLS/SSL in one of your Kubernetes manifests. The recommended practice is use of secure HTTP for each team's development and production environment. Enabling TLS ensures secure communication between cluster components.. For examples of Kubernetes security anti-patterns we are following our peer-reviewed publication on Kubernetes security best practices (https://arxiv.org/pdf/2006.15275.pdf).

Location of security anti-pattern:

https://github.com/stefanprodan/podinfo/blob/ea292aa958c5e348266518af2261dc04d6270439/deploy/webapp/frontend/deployment.yaml#L45

**Comment by stefanprodan** [comment]
> Enabling TLS ensures secure communication between cluster components

You do realise that podinfo is not a cluster component right? TLS is fully supported in podinfo when using a service mesh or cert-manager.

**Comment by akondasif** [comment]
Thanks for the feedback.
