### ISSUE TITLE
k8s recommended labels

### ISSUE THREAD

**Issue by knweiss** [stefanprodan/podinfo#173]
I have a nitpicking question regarding label best practices: What about using the [k8s recommended labels AKA common labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/) instead of (or in addition to) the private label `app`?

The current configuration triggers this kubescape warning: [C-0077 - K8s common labels usage](https://hub.armo.cloud/docs/c-0077)

Maybe `kustomize/kustomization.yaml` could be extended like this:
```
+commonLabels:
+  app.kubernetes.io/name: "podinfo"
+  app.kubernetes.io/managed-by: "kustomize"
...
```

**Comment by stefanprodan** [comment]
Podinfo is used by many project for e2e testing and docs (CNCF Flux, Flagger, Linkerd, etc), changing the labels is not something I would consider as they are immutable.
