### ISSUE TITLE
stefanprodan.github.io is unaccessible

### ISSUE THREAD

**Issue by chrislin22** [stefanprodan/podinfo#218]
`stefanprodan.github.io` is unaccessible

**Comment by chrislin22** [comment]
sorry, I meant use browser to hit either `https://github.com/stefanprodan/podinfo` or `https://github.com/stefanprodan` is not working. The index.yaml does work. Is it a desired behavior? Thanks

**Comment by stefanprodan** [comment]
Is it a desired behavior? 

Yes, the sole reason that URL exists is to server the Helm charts for podinfo.

**Comment by chrislin22** [comment]
cool thanks
