### ISSUE TITLE
Support dynamic paths endpoint?

### ISSUE THREAD

**Issue by merusso** [stefanprodan/podinfo#229]
Would it be desirable to add a podinfo endpoint that accepts dynamic paths?

For example, pattern /echo/** would accept /echo, /echo/foo, echo/foo/bar, etc. All paths would be handled the same way.

For now, I'm using k8s echoserver (registry.k8s.io/e2e-test-images/echoserver:2.5) to test this, as it always responds the same way for any URI path.

I use this feature to test arbitrary path patterns passed through a reverse proxy.

**Comment by stefanprodan** [comment]
Yes dynamic paths for `echo` would be great!

**Comment by jjchambl** [comment]
@stefanprodan I've opened https://github.com/stefanprodan/podinfo/pull/271 to address this. Take a look and let me know what you think.

**Comment by jjchambl** [comment]
@stefanprodan @merusso since the PR for this feature has been merged, can we close this issue?

**Comment by stefanprodan** [comment]
Ah yes, forgot to close it, thanks for the reminder.
