### ISSUE TITLE
Add gPRC API

### ISSUE THREAD

**Issue by stefanprodan** [stefanprodan/podinfo#24]
Implement a gPRC version of the API (on a different port) for podinfo and generate the client in podcli.

**Comment by clock21am** [comment]
@stefanprodan I would like to take up this issue.

**Comment by stefanprodan** [comment]
thanks @clock21am

**Comment by mjallday** [comment]
looks like https://github.com/grpc/grpc-go/tree/master/health will give us the health check mentioned in https://github.com/weaveworks/flagger/pull/278 for free so that's an easy win.
