### ISSUE TITLE
Adding gRPC apis functionality

### ISSUE THREAD

**Issue by JayKaku** [stefanprodan/podinfo#318]
As there is already a server written for gRPC, gRPC apis (replicating HTTP ones) would be a valuable addition to the suite as a whole. I would like to discuss further on this and contribute. Thanks.

**Comment by Rachitmehrotra** [comment]
@stefanprodan we need grpc server for our use case is it possible for you to allow him to raise PR.

**Comment by stefanprodan** [comment]
Sure let's do first `version` and `echo` to see how it goes.

**Comment by JayKaku** [comment]
#322 here is the new PR with 2 commits as you suggested, the issue with the previous one being the git history was very entangled

**Comment by stefanprodan** [comment]
In https://github.com/stefanprodan/podinfo/pull/322 we covered the following APIs:
- `echo`
- `version`
- `panic`
