### ISSUE TITLE
Confusion regarding comments on graceful shutdown

### ISSUE THREAD

**Issue by duxinxiao** [stefanprodan/podinfo#319]
https://github.com/stefanprodan/podinfo/blob/d9bc6301e9b614cbe24e190396bc574d51a2427d/pkg/signals/shutdown.go#L51
"wait for Kubernetes readiness probe to remove this instance from the load balancer"
I think this is not about waiting for the readiness probe, as the readiness probe takes a long time to take effect. It seems that this is actually because the SIGTERM and removal from service happen concurrently, and we need to wait a moment?

**Comment by stefanprodan** [comment]
This is an old hack for service mesh sidecars, after many years Kubernetes has finally introduce native sidecar support https://kubernetes.io/blog/2023/08/25/native-sidecar-containers/ but it's alpha. Once this goes GA, we can remove this artificial delay.

**Comment by duxinxiao** [comment]
I think we should have this line of code even if native sidecar goes GA. 
https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-termination, It's noted that "At the same time as the kubelet is starting graceful shutdown of the Pod, the control plane evaluates whether to remove that shutting-down Pod from EndpointSlice (and Endpoints)." This suggests there could be a period where a terminating pod may still receive requests from the service. so it's better wait for a moment
my confusion is that I think all graceful shutdown process is no business with readiness probe, because it will take at least periodSeconds*failureThreshold, which is longer than ServerShutdownTimeout.

Thank you for your patient

**Comment by stefanprodan** [comment]
Yes good point, can you please open a PR to update the comment with the link to kube doc.
