### ISSUE TITLE
Cyan background

### ISSUE THREAD

**Issue by ybizeul** [stefanprodan/podinfo#47]
Not sure that's normal, but I just tried podinfo for the first time and it displays a kind of agressive cyan background instead of the darker blue.

I do see where it comes from, see the following code :

```
<div class="v-parallax" id="parallax-hero" style="height: 500px; background-color: cyan;">
```

![Screenshot 2020-03-24 at 09 23 58](https://user-images.githubusercontent.com/182035/77403909-3c81cd00-6db1-11ea-87aa-e620ee52f45f.png)

**Comment by stefanprodan** [comment]
How did you deployed it? In the kustomization deployment the background is set like this https://github.com/stefanprodan/podinfo/blob/master/kustomize/deployment.yaml#L51

**Comment by ybizeul** [comment]
Thanks I was just using a bare deployment without any parameters.
