### ISSUE TITLE
support for arm / arm64

### ISSUE THREAD

**Issue by HaveFun83** [stefanprodan/podinfo#68]
Thanks a lot for this great project here.
Is it possible to build multiarch images [arm / arm64] for it?

**Comment by stefanprodan** [comment]
I tried but after 20 minutes docker buildx fails with a cryptic error https://github.com/stefanprodan/podinfo/runs/692608910

**Comment by stefanprodan** [comment]
On a 2nd try it worked, here is the image `stefanprodan/podinfo:multiarch`, it took 25m 😱

**Comment by HaveFun83** [comment]
@stefanprodan thanks a lot

**Comment by stefanprodan** [comment]
@HaveFun83 I've released podinfo 4.0.0 with multi-arch support. Can you please test it out on ARM devices and tell me if it works? Thanks

**Comment by HaveFun83** [comment]
> @HaveFun83 I've released podinfo 4.0.0 with multi-arch support. Can you please test it out on ARM devices and tell me if it works? Thanks

Tested on rpi 4 on arm64 via helm install works like a charm. :+1:
